version: '3.8'

services:
  server-app:
    image: erlang:21
    container_name: server
    working_dir: /app
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ./src:/app/src
      - ./include:/app/include
      - ./config:/app/config
      - ./rebar.config:/app/rebar.config
      - ./scripts/run_server.sh:/app/scripts/run_server.sh
      - ~/.erlang.cookie:/root/.erlang.cookie:ro
      - server_data:/app/data
    command: bash /app/scripts/run_server.sh
    restart: unless-stopped
    networks:
      server-network:
        ipv4_address: 172.40.0.2
    stdin_open: true
    tty: true

  # sipp-tester1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sipp
  #   image: mysipp
  #   container_name: sipp-tester1
  #   environment:
  #     - TZ=Asia/Novosibirsk
  #   volumes:
  #     - ./test:/test:ro
  #   command: sipp -sf /test/message_test.xml -inf /test/test_data.csv -m 15 172.30.0.2:5060
  #   working_dir: /
  #   networks:
  #     poll-network:
  #       ipv4_address: 172.30.0.3
  #   depends_on:
  #     - poll-app

  # sipp-tester2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sipp
  #   image: mysipp
  #   container_name: sipp-tester2
  #   environment:
  #     - TZ=Asia/Novosibirsk
  #   volumes:
  #     - ./test:/test:ro
  #   command: sipp -sf /test/message_test.xml -inf /test/test_data.csv -r 20 -l 80 -m 500 172.30.0.2:5060
  #   working_dir: /
  #   networks:
  #     poll-network:
  #       ipv4_address: 172.30.0.4
  #   depends_on:
  #     - poll-app

volumes:
  server_data:

networks:
  server-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24