version: '3.8'

services:
  server-app1:
    image: erlang:21
    container_name: server1
    hostname: node1
    working_dir: /app
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ./src:/app/src
      - ./include:/app/include
      - ./config/sys1.config:/app/config/sys.config
      - ./rebar.config:/app/rebar.config
      - ./scripts/run_server1.sh:/app/scripts/run_server.sh
      - ~/.erlang.cookie:/root/.erlang.cookie:ro
      - server_data1:/app/data
    command: bash /app/scripts/run_server.sh
    restart: unless-stopped
    networks:
      server-network:
        ipv4_address: 172.40.0.2
    stdin_open: true
    tty: true

  server-app2:
    image: erlang:21
    container_name: server2
    hostname: node2
    working_dir: /app
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ./src:/app/src
      - ./include:/app/include
      - ./config/sys2.config:/app/config/sys.config
      - ./rebar.config:/app/rebar.config
      - ./scripts/run_server2.sh:/app/scripts/run_server.sh
      - ~/.erlang.cookie:/root/.erlang.cookie:ro
      - server_data2:/app/data
    command: bash /app/scripts/run_server.sh
    restart: unless-stopped
    networks:
      server-network:
        ipv4_address: 172.40.0.3
    stdin_open: true
    tty: true
    # depends_on:
    #   - server-app1

  sip-balancer:
    image: alpine:latest
    container_name: sip-balancer
    privileged: true # Дает полный доступ к iptables и сетевым модулям ядра
    sysctls:
      - net.ipv4.ip_forward=1 # Docker сам включит форвардинг при старте
    volumes:
      - ./scripts/balancer.sh:/balancer.sh:ro
    command: sh -c "apk add --no-cache iptables curl conntrack-tools && sh /balancer.sh"
    networks:
      server-network:
        ipv4_address: 172.40.0.4
    ports:
      - "5060:5060/udp"
    restart: unless-stopped
    depends_on:
      - server-app1
      - server-app2


  # sipp-tester1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sipp
  #   image: mysipp
  #   container_name: sipp-tester1
  #   environment:
  #     - TZ=Asia/Novosibirsk
  #   volumes:
  #     - ./test:/test:ro
  #   command: sipp -sf /test/message_test.xml -inf /test/test_data.csv -m 15 172.30.0.2:5060
  #   working_dir: /
  #   networks:
  #     poll-network:
  #       ipv4_address: 172.30.0.3
  #   depends_on:
  #     - poll-app

  # sipp-tester2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sipp
  #   image: mysipp
  #   container_name: sipp-tester2
  #   environment:
  #     - TZ=Asia/Novosibirsk
  #   volumes:
  #     - ./test:/test:ro
  #   command: sipp -sf /test/message_test.xml -inf /test/test_data.csv -r 20 -l 80 -m 500 172.30.0.2:5060
  #   working_dir: /
  #   networks:
  #     poll-network:
  #       ipv4_address: 172.30.0.4
  #   depends_on:
  #     - poll-app

volumes:
  server_data1:
  server_data2:

networks:
  server-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24